### PR TITLE
Create example_doc

### PR DESCRIPTION
**Pull request by chenjs**
Hi, can someone tell me what doc type should I choose? 

md ?
txt ?
or ms word format ?

### CODE REVIEW

**Comment by hellochenjs** [comment]
Let's use markdown, OK ?

**Comment by chenjs** [comment]
markdown, I like :+1:  @hellochenjs

**Comment by chenjs** [comment]
I'v add content to document. pls check.

**Comment by chenjs** [comment]
@hellochenjs

**Comment by hellochenjs** [comment]
:+1:

**Pull request merged**
